[package]
name = "radio"
description = "Generic traits for embedded packet radio devices"
repository = "https://github.com/ryankurte/rust-radio"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
license = "MIT"
edition = "2018"
version = "0.7.0"

[package.metadata.docs.rs]
all-features = true

[features]
async-await = [ ]
mock = [ "embedded-hal-mock" ]
all = [ "async-await", "async-std", "mock" ]
default = []

[dependencies]
nb = "0.1.2"
log = "0.4.8"
embedded-hal = "0.2.3"
async-trait = "0.1.22"

[dependencies.chrono]
version = "*"
default_features = false

[dependencies.embedded-hal-mock]
version = "0.7.1"
optional = true

[dependencies.async-std]
version = "1.4.0"
optional = true



[dev-dependencies]
async-std = "1.4.0"

