[package]
name = "radio"
description = "Generic traits for embedded packet radio devices"
repository = "https://github.com/ryankurte/rust-radio"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
license = "MIT"
edition = "2018"
version = "0.4.2"

[features]
async-await = [ "core" ]
mock = [ "embedded-hal-mock" ]
default = []

[package.metadata.docs.rs]
all-features = true

[dependencies]
nb = "0.1.2"
log = "0.4.8"
embedded-hal = "0.2.3"
async-trait = "0.1.22"

# We have to override core to support futures in a no-std package
[dependencies.core]
package = "core-futures-tls"
version = "0.1.0"
optional = true

[dependencies.embedded-hal-mock]
version = "0.7.1"
optional = true

[dev-dependencies]
async-std = "1.4.0"

[patch.crates-io]
embedded-hal-mock = { path = "../embedded-hal-mock" }
