[package]
name = "radio"
description = "Generic traits for embedded packet radio devices"
repository = "https://github.com/ryankurte/rust-radio"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
license = "MIT"
version = "0.3.1"

[dependencies]
nb = "0.1.2"
log = "0.4.6"
embedded-hal = "0.2.3"

